### ISSUE TITLE
[Duplicate] Issue #163

### ISSUE THREAD

**Issue by no-name-provided** [jaredlll08/Controlling#172]
Not much to say. Controlling consistently crashes Minecraft 1.19.3 when installed and the key binds screen is opened. Issue persisted across multiple versions of Forge. No crash after removing controlling.

Error indicates an issue with the search box. "Justleveling" also came up in the Minecraft log - possible mod conflict?
After uninstalling controlling, Architectury was also flagged in the Minecraft log with a keymapping issue. Excerpt below:

<details>
[00:10:13] [Worker-Main-8/WARN] [de.ar.re.cl.ke.fo.KeyMappingRegistryImpl/]: Key mapping key.observable.profile registered after event
java.lang.RuntimeException: null
	at dev.architectury.registry.client.keymappings.forge.KeyMappingRegistryImpl.register(KeyMappingRegistryImpl.java:47) ~[architectury-7.1.86-forge.jar%23248!/:?] {re:classloading}
	at dev.architectury.registry.client.keymappings.KeyMappingRegistry.register(KeyMappingRegistry.java) ~[architectury-7.1.86-forge.jar%23248!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at observable.Observable.clientInit(Observable.java:152) ~[observable-4.3.3.jar%23318!/:?] {re:mixin,re:classloading}
	at observable.forge.ObservableForge.onClientInit(ObservableForge.java:28) ~[observable-4.3.3.jar%23318!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23109!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.3-44.1.23.jar%23356!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.3-44.1.23.jar%23355!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
</details>

No apparent problems setting other keybinds or playing the game with Architectury installed.

Crash log: https://paste.ee/p/zK1bt

**Comment by jaredlll08** [comment]
You are missing the Searchables dependency:
https://legacy.curseforge.com/minecraft/mc-mods/searchables/files/4542393

**Comment by no-name-provided** [comment]
Thanks for the update. Please change the title of this bug report to "Mandatory Searchables dependency not being caught by FML and reported when Minecraft launches" and resolve. If relevant, please open a new bug report titled "Crashes with incorrect error if Searchables dependency is missing".

As an additional suggestion, consider listing mandatory dependencies, particularly inflexible dependencies like library mods, on your curseforge information page: https://www.curseforge.com/minecraft/mc-mods/controlling. This is a common practice that helps insulate end users from implementation details. (Yes, I am aware of the dependencies page. This is just a suggestion.)
