### ISSUE TITLE
[1.15.2] NoClassDefFoundError

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [jaredlll08/Controlling#48]
MC 1.15.2
forge 31.0.1
Controlling 6.0.0

java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/config/GuiUtils
	at com.blamejared.controlling.client.gui.GuiCheckBox.renderButton(GuiCheckBox.java:33) ~[?:6.0.0] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.render(Widget.java:79) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.blamejared.controlling.client.gui.GuiNewControls.render(GuiNewControls.java:200) ~[?:6.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:365) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.0.1.jar:31.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.client.config.GuiUtils
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221] {}
	... 18 more

**Comment by Rumpelstiltskinny** [comment]
...oops, I now see that Controlling 6.0.0 is only for 1.15.1...woulda been handy if that was in the toml.

**Comment by jaredlll08** [comment]
a 1.15.2 version is on curseforge, 6.1.0
