### ISSUE TITLE
Minecraft se me crashea al intentar entrar en controles

### ISSUE THREAD

**Issue by Carlos81111** [jaredlll08/Controlling#88]
Time: 8/19/21 3:27 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:154)
	at net.minecraft.client.settings.KeyBinding.compareTo(KeyBinding.java:14)
	at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.ComparableTimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at net.minecraft.client.gui.GuiKeyBindingList.<init>(GuiKeyBindingList.java:28)
	at net.minecraft.client.gui.GuiControls.func_73866_w_(GuiControls.java:31)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraft.client.gui.GuiOptions.func_146284_a(SourceFile:152)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1752)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jaredlll08** [comment]
Mc version?
Controlling version?

**Comment by jaredlll08** [comment]
Closing due to no information.

The crash log doesn't even mention controlling either.
